/**
 * The curriculum: the single source of truth for the learning journey.
 *
 * Sections 1-11 map one-to-one onto the book chapters, so "Section 5" always
 * means "Chapter 5". Parts are a display grouping only and never renumber or
 * reorder sections. The AI section is an appendix: number 12, bookChapter 0,
 * and excluded from progress.
 *
 * Lesson `id` is the stable progress key and never changes. Lesson `slug` is
 * the URL segment. Both are explicit fields - neither is derived from the
 * title at runtime, so retitling a lesson cannot break a link or orphan
 * a learner progress record.
 */

import { BarChart3, BookOpen, Database, Fingerprint, Gavel, Network, Route, Scale, Send, Sparkles, Target, Tv } from "lucide-react";
import type { Part } from "./types";

export const curriculum: Part[] = [
  {
    id: "foundations",
    title: "Part I — Foundations",
    subtitle: "The words everyone around you assumes you already know.",
    sections: [
      {
        id: "basics",
        number: 1,
        bookChapter: 1,
        title: "Basics",
        summary: "The vocabulary of digital advertising: slots, creatives, impressions, clicks, conversions, and the three ways an ad is priced.",
        icon: BookOpen,
        lessons: [
          {
            id: "basics-what-is-adtech",
            slug: "what-is-adtech",
            title: "What AdTech actually is",
            minutes: 7,
            summary: "What the AdTech stack is, and what it does for the advertiser buying and the publisher selling.",
          },
          {
            id: "basics-ad-slots-space-and-inventory",
            slug: "ad-slots-space-and-inventory",
            title: "Slots, space, and inventory",
            minutes: 9,
            summary: "Tell apart the container on the page, the ad that fills it, and the publisher's whole supply — premium, remnant, and long tail.",
          },
          {
            id: "basics-creatives",
            slug: "creatives",
            title: "The creative: what actually shows up",
            minutes: 6,
            summary: "The file that becomes the ad — image, video, or audio — and the formats each one ships in.",
          },
          {
            id: "basics-impressions-and-viewability",
            slug: "impressions-and-viewability",
            title: "Served vs actually seen",
            minutes: 9,
            summary: "Why an ad that was counted is not the same as an ad that was seen, and where the IAB draws the line.",
          },
          {
            id: "basics-click-to-conversion",
            slug: "click-to-conversion",
            title: "Click, landing page, conversion",
            minutes: 10,
            summary: "Follow one person from the click, through the landing page, to the action the advertiser is paying for.",
          },
          {
            id: "basics-pricing-models",
            slug: "pricing-models",
            title: "Who pays for what: CPM, CPC, CPA",
            minutes: 9,
            summary: "The three ways an ad is priced, and how each one moves risk between the advertiser and the publisher.",
          },
        ],
      },
    ],
  },
  {
    id: "supply-chain",
    title: "Part II — The Supply Chain",
    subtitle: "Who sits between an advertiser and a page, where ads appear, and how one gets delivered.",
    sections: [
      {
        id: "technology",
        number: 2,
        bookChapter: 2,
        title: "The platforms",
        summary: "The systems between an advertiser and a page — who buys, who sells, who matches them, and who keeps them honest.",
        icon: Network,
        lessons: [
          {
            id: "technology-why-there-is-a-stack",
            slug: "why-there-is-a-stack",
            title: "Why there is a stack between an advertiser and a page",
            minutes: 6,
            summary: "See one impression travel the whole chain in about 100 milliseconds before meeting any platform on its own.",
          },
          {
            id: "technology-the-buy-side",
            slug: "the-buy-side",
            title: "The buy side: DSPs and the data that feeds a bid",
            minutes: 11,
            summary: "How a demand-side platform decides whether to bid and how much, and where its audience data comes from.",
          },
          {
            id: "technology-the-sell-side-and-the-auction",
            slug: "the-sell-side-and-the-auction",
            title: "The sell side: SSPs, exchanges and how the auction is run",
            minutes: 11,
            summary: "How a publisher packages and sells its inventory, sets a floor price, and lets an exchange run the auction.",
          },
          {
            id: "technology-ad-servers-and-ad-networks",
            slug: "ad-servers-and-ad-networks",
            title: "Getting the ad onto the page: ad servers and ad networks",
            minutes: 11,
            summary: "Who stores the creative, picks the ad and counts it — and what an ad network adds on top.",
          },
          {
            id: "technology-who-runs-the-stack",
            slug: "who-runs-the-stack",
            title: "Who runs the stack: walled gardens, agencies, trading desks and AdOps",
            minutes: 9,
            summary: "The companies and job titles behind the platforms, and which middlemen a walled garden removes.",
          },
          {
            id: "technology-verification-and-standards",
            slug: "verification-and-standards",
            title: "Did the ad really run? Verification, measurement and IAB standards",
            minutes: 9,
            summary: "How buyers check an ad ran where it was meant to, and why shared IAB definitions make that possible.",
          },
          {
            id: "technology-dynamic-creative-optimization",
            slug: "dynamic-creative-optimization",
            title: "Dynamic creative optimization: assembling the ad while the auction runs",
            minutes: 8,
            summary: "How a personalised ad is built for one person in the moment after the bid is won.",
          },
        ],
      },
      {
        id: "channels",
        number: 3,
        bookChapter: 3,
        title: "Channels and formats",
        summary: "Where ads appear and what form they take: web, native, video, audio, social, in-app, TV, outdoor and search.",
        icon: Tv,
        lessons: [
          {
            id: "channels-mediums-vs-channels-and-the-web",
            slug: "mediums-vs-channels-and-the-web",
            title: "Mediums vs channels, and how a web ad actually loads",
            minutes: 11,
            summary: "The difference between what an ad is and where it travels, then the exact sequence a browser runs to load one.",
          },
          {
            id: "channels-native-ads",
            slug: "native-ads",
            title: "Native ads: blending in, and the disclosure that keeps it honest",
            minutes: 7,
            summary: "Ads built to look like the content around them, and the labelling rules that keep that honest.",
          },
          {
            id: "channels-video-ads-and-standards",
            slug: "video-ads-and-standards",
            title: "Video ads and the standards that deliver them",
            minutes: 9,
            summary: "Why a video ad goes to the player rather than the page, and what VAST, VMAP and SIMID each do.",
          },
          {
            id: "channels-rich-media-and-audio",
            slug: "rich-media-and-audio",
            title: "Rich media and audio: formats that do more than sit there",
            minutes: 9,
            summary: "Interactive formats, and audio spots that rewrite themselves for the listener's place, time and weather.",
          },
          {
            id: "channels-mobile-and-social",
            slug: "mobile-and-social",
            title: "In-app and social: SDKs and walled gardens",
            minutes: 9,
            summary: "Why an in-app ad needs an SDK instead of a tag, and what social platforms can target that the open web cannot.",
          },
          {
            id: "channels-advanced-tv-dooh-and-search",
            slug: "advanced-tv-dooh-and-search",
            title: "Big screens and high intent: advanced TV, DOOH and search",
            minutes: 10,
            summary: "Streaming TV, screens in public places, and search: three very different ways to reach someone.",
          },
          {
            id: "channels-ai-and-cross-channel",
            slug: "ai-and-cross-channel",
            title: "One message everywhere, and what AI is doing to it",
            minutes: 8,
            summary: "One brand message adapted for every surface, and what AI now automates in that work.",
          },
        ],
      },
      {
        id: "adserving",
        number: 4,
        bookChapter: 4,
        title: "Ad serving",
        summary: "How one ad is requested, chosen, delivered and counted — usually in under a tenth of a second.",
        icon: Send,
        lessons: [
          {
            id: "adserving-what-an-ad-server-is",
            slug: "what-an-ad-server-is",
            title: "What an ad server actually is",
            minutes: 5,
            summary: "The four jobs of an ad server: store the creative, select it, deliver it, and track what happened.",
          },
          {
            id: "adserving-four-stages-of-a-served-ad",
            slug: "four-stages-of-a-served-ad",
            title: "The four stages of serving one ad",
            minutes: 11,
            summary: "Walk the request, the decision, the delivery and the tracking of a single directly sold ad.",
          },
          {
            id: "adserving-when-the-auction-joins-in",
            slug: "when-the-auction-joins-in",
            title: "When an auction joins the flow",
            minutes: 7,
            summary: "What changes in that flow when the impression is auctioned instead of sold in advance.",
          },
          {
            id: "adserving-first-party-vs-third-party",
            slug: "first-party-vs-third-party",
            title: "First-party vs third-party ad servers",
            minutes: 9,
            summary: "The publisher's ad server and the advertiser's ad server: the same technology doing opposite jobs.",
          },
          {
            id: "adserving-anatomy-of-an-ad-server",
            slug: "anatomy-of-an-ad-server",
            title: "Inside the box: the nine ad-server subsystems",
            minutes: 12,
            summary: "The nine parts inside an ad server, from the decision engine to frequency control.",
          },
          {
            id: "adserving-ad-tags-and-ad-markup",
            slug: "ad-tags-and-ad-markup",
            title: "Ad tags and ad markup: the code in the slot",
            minutes: 7,
            summary: "The code that sits in the slot waiting, and the code that comes back to fill it.",
          },
        ],
      },
    ],
  },
  {
    id: "running-a-campaign",
    title: "Part III — Running a Campaign",
    subtitle: "Choosing who sees an ad, counting what happened, and buying the impression in the first place.",
    sections: [
      {
        id: "targeting",
        number: 5,
        bookChapter: 5,
        title: "Targeting and budget",
        summary: "Choosing who sees an ad — by page, place, device, behaviour or past visit — and keeping the spend under control.",
        icon: Target,
        lessons: [
          {
            id: "targeting-why-targeting-exists",
            slug: "why-targeting-exists",
            title: "Why targeting exists and the six ways to do it",
            minutes: 5,
            summary: "Why advertisers narrow their audience at all, and the six signals they narrow it by.",
          },
          {
            id: "targeting-contextual-and-the-page",
            slug: "contextual-and-the-page",
            title: "Contextual targeting: buying the page, not the person",
            minutes: 11,
            summary: "Targeting what a page is about rather than who is reading it, and the IAB categories that make that possible.",
          },
          {
            id: "targeting-geo-device-and-timing",
            slug: "geo-device-and-timing",
            title: "Targeting what the ad request tells you: place, device and time",
            minutes: 8,
            summary: "What the ad request alone reveals: location, device, browser and the time of day.",
          },
          {
            id: "targeting-behavioral-audiences",
            slug: "behavioral-audiences",
            title: "Behavioral targeting: from raw events to an audience",
            minutes: 12,
            summary: "How browsing events become a profile, and how profiles become a targetable audience.",
          },
          {
            id: "targeting-retargeting-and-demographics",
            slug: "retargeting-and-demographics",
            title: "Retargeting and demographic targeting",
            minutes: 10,
            summary: "Following a shopper to the next site, and the harder problem of knowing their age or income.",
          },
          {
            id: "targeting-budget-control",
            slug: "budget-control",
            title: "Controlling spend: caps, pacing and frequency",
            minutes: 12,
            summary: "Caps, pacing and frequency limits — the three dials that stop a campaign wasting money.",
          },
        ],
      },
      {
        id: "tracking",
        number: 6,
        bookChapter: 6,
        title: "Tracking and reporting",
        summary: "How impressions, clicks and conversions are counted, reported, and reconciled when two systems disagree.",
        icon: BarChart3,
        lessons: [
          {
            id: "tracking-impressions-and-clicks",
            slug: "impressions-and-clicks",
            title: "How impressions and clicks are counted",
            minutes: 10,
            summary: "The 1×1 pixel that records an impression, and the redirect chain that records a click.",
          },
          {
            id: "tracking-conversions-ctc-vtc-and-attribution-windows",
            slug: "conversions-ctc-vtc-and-attribution-windows",
            title: "Conversions, CTC vs VTC, and attribution windows",
            minutes: 9,
            summary: "Conversions after a click versus after a view, and the window in which either still counts.",
          },
          {
            id: "tracking-client-side-vs-server-side-and-counting-methods",
            slug: "client-side-vs-server-side-and-counting-methods",
            title: "Pixels, piggybacking, server-side tracking, and who counts the impression",
            minutes: 11,
            summary: "Pixels, piggybacked vendor tags and server-to-server calls, and why two servers count the same ad differently.",
          },
          {
            id: "tracking-viewability-and-verification",
            slug: "viewability-and-verification",
            title: "Was the ad actually seen? Viewability and verification",
            minutes: 6,
            summary: "Proving an ad was on screen long enough for a real person to have seen it.",
          },
          {
            id: "tracking-metrics-and-effective-metrics",
            slug: "metrics-and-effective-metrics",
            title: "Reading the report: metrics, effective metrics, and ROI",
            minutes: 11,
            summary: "The metrics on every report, and why eCPM, eCPC and eCPA let you compare deals priced differently.",
          },
          {
            id: "tracking-dimensions-filtering-and-report-limits",
            slug: "dimensions-filtering-and-report-limits",
            title: "Slicing a report: dimensions, filters, and what reports can't tell you",
            minutes: 8,
            summary: "Breaking a report down by dimension and filter, and what delays, time zones and retention quietly hide.",
          },
          {
            id: "tracking-discrepancies-and-reconciliation",
            slug: "discrepancies-and-reconciliation",
            title: "When the two reports disagree: discrepancies and reconciliation",
            minutes: 9,
            summary: "When the publisher's numbers and the advertiser's numbers disagree, and how big a gap is normal.",
          },
        ],
      },
      {
        id: "mediabuying",
        number: 7,
        bookChapter: 7,
        title: "Media buying",
        summary: "The three ways media is bought — guaranteed, private, open auction — and how a real-time auction settles in milliseconds.",
        icon: Gavel,
        lessons: [
          {
            id: "mediabuying-programmatic-basics",
            slug: "programmatic-basics",
            title: "How media gets bought: manual deals to programmatic",
            minutes: 8,
            summary: "What programmatic replaced, and when a guaranteed deal still beats an auction.",
          },
          {
            id: "mediabuying-rtb-auction-in-100ms",
            slug: "rtb-auction-in-100ms",
            title: "Real-time bidding: one impression, 100 milliseconds",
            minutes: 11,
            summary: "Follow one impression through a real-time auction, from page load to rendered ad.",
          },
          {
            id: "mediabuying-inside-a-bid-request",
            slug: "inside-a-bid-request",
            title: "Inside a bid request: OpenRTB and what DSPs actually see",
            minutes: 7,
            summary: "What a buyer actually receives about an impression, field by field, in the industry's shared format.",
          },
          {
            id: "mediabuying-auction-dynamics-and-floors",
            slug: "auction-dynamics-and-floors",
            title: "What the winner actually pays: first price, second price and floors",
            minutes: 9,
            summary: "First price, second price, bid shading and floor prices — what the winner really pays and why.",
          },
          {
            id: "mediabuying-publishers-waterfall",
            slug: "publishers-waterfall",
            title: "The publisher's waterfall and why impressions go unsold",
            minutes: 10,
            summary: "How publishers sold leftover inventory before header bidding, and why so many impressions went unfilled.",
          },
          {
            id: "mediabuying-header-bidding",
            slug: "header-bidding",
            title: "Header bidding: everyone bids at once",
            minutes: 11,
            summary: "Asking every buyer at the same time instead of one after another, and what it costs in page speed.",
          },
          {
            id: "mediabuying-campaign-optimization",
            slug: "campaign-optimization",
            title: "Keeping a live campaign healthy: manual, automated, hybrid",
            minutes: 8,
            summary: "Tuning a running campaign by hand, by algorithm, or with both.",
          },
        ],
      },
    ],
  },
  {
    id: "who-and-why",
    title: "Part IV — Knowing Who, and Proving Why",
    subtitle: "Recognising a person across the web, turning their behaviour into audiences, and deciding what earned the sale.",
    sections: [
      {
        id: "identity",
        number: 8,
        bookChapter: 8,
        title: "Identity and privacy",
        summary: "How a person is recognised across sites and devices, and the privacy rules reshaping every method.",
        icon: Fingerprint,
        lessons: [
          {
            id: "identity-cookies-and-the-stateless-web",
            slug: "cookies-and-the-stateless-web",
            title: "Cookies and how the web remembers you",
            minutes: 9,
            summary: "What a cookie is, why the web needed one, and the difference between first-party and third-party.",
          },
          {
            id: "identity-life-after-third-party-cookies",
            slug: "life-after-third-party-cookies",
            title: "Life after third-party cookies: universal IDs",
            minutes: 8,
            summary: "Why matching users by syncing cookies is failing, and what universal IDs replace it with.",
          },
          {
            id: "identity-mobile-and-in-app",
            slug: "mobile-and-in-app",
            title: "Mobile and in-app identity",
            minutes: 7,
            summary: "Device advertising IDs, the app tracking prompt, and what low opt-in did to measurement.",
          },
          {
            id: "identity-cross-device-resolution",
            slug: "cross-device-resolution",
            title: "Cross-device identity resolution",
            minutes: 12,
            summary: "Linking one person's phone, laptop and tablet — either with certainty or with statistics.",
          },
          {
            id: "identity-privacy-rules-and-consent",
            slug: "privacy-rules-and-consent",
            title: "The rules: privacy regulation and consent",
            minutes: 7,
            summary: "GDPR, CCPA and consent prompts, and which identifiers go dark under each.",
          },
          {
            id: "identity-privacy-preserving-tech",
            slug: "privacy-preserving-tech",
            title: "Privacy-preserving tech: Sandbox and clean rooms",
            minutes: 9,
            summary: "Measuring and targeting without any single person's data leaving the room.",
          },
          {
            id: "identity-fingerprinting-and-contextual",
            slug: "fingerprinting-and-contextual",
            title: "Alternatives: fingerprinting and contextual",
            minutes: 7,
            summary: "Two fallbacks when there is no identifier: guess the device, or forget the person and read the page.",
          },
        ],
      },
      {
        id: "data",
        number: 9,
        bookChapter: 9,
        title: "Data and audiences",
        summary: "Where audience data comes from, how a platform turns raw events into profiles, and how segments get built and used.",
        icon: Database,
        lessons: [
          {
            id: "data-three-types-of-data",
            slug: "three-types-of-data",
            title: "First-, second- and third-party data",
            minutes: 9,
            summary: "The three kinds of audience data, and why accuracy falls as the distance from the source grows.",
          },
          {
            id: "data-where-data-comes-from",
            slug: "where-data-comes-from",
            title: "Where the data lives, and why it is scattered",
            minutes: 8,
            summary: "The online and offline systems customer data sits in, and what it costs to leave them separate.",
          },
          {
            id: "data-how-a-dmp-collects-data",
            slug: "how-a-dmp-collects-data",
            title: "How a DMP actually collects data",
            minutes: 10,
            summary: "Pixels, tags, tag managers and server-to-server calls — the four ways data arrives.",
          },
          {
            id: "data-normalization-and-profiles",
            slug: "normalization-and-profiles",
            title: "Turning raw events into one user profile",
            minutes: 11,
            summary: "Cleaning messy events into one profile per person, and merging the duplicates.",
          },
          {
            id: "data-taxonomies-and-segments",
            slug: "taxonomies-and-segments",
            title: "Taxonomies and building an audience segment",
            minutes: 11,
            summary: "Naming data consistently, then building an audience with rules, exclusions and recency.",
          },
          {
            id: "data-activating-segments",
            slug: "activating-segments",
            title: "Activating segments, and DMP versus CDP",
            minutes: 7,
            summary: "Sending a segment somewhere it can be used, and where a DMP stops and a CDP begins.",
          },
        ],
      },
      {
        id: "attribution",
        number: 10,
        bookChapter: 10,
        title: "Attribution",
        summary: "Deciding which ad, click or view gets credit for a sale — across channels, across devices, and offline.",
        icon: Route,
        lessons: [
          {
            id: "attribution-what-attribution-is",
            slug: "what-attribution-is",
            title: "What attribution is, and inter- vs intra-channel",
            minutes: 6,
            summary: "What attribution claims to answer, and the difference between crediting across channels and within one.",
          },
          {
            id: "attribution-how-online-attribution-works",
            slug: "how-online-attribution-works",
            title: "How the platform knows where you came from",
            minutes: 9,
            summary: "The referrer header, the five ways traffic gets classified, and when the referrer disappears.",
          },
          {
            id: "attribution-single-touch-models",
            slug: "single-touch-models",
            title: "Single-touch models: last click, last non-direct, first click",
            minutes: 8,
            summary: "Giving all the credit to one touchpoint, and the three ways of choosing which one.",
          },
          {
            id: "attribution-multi-touch-models",
            slug: "multi-touch-models",
            title: "Multi-touch models: linear, time decay, position based, custom",
            minutes: 10,
            summary: "Splitting credit across the whole journey — evenly, by recency, or by position.",
          },
          {
            id: "attribution-cross-device",
            slug: "cross-device",
            title: "Following a user across devices",
            minutes: 8,
            summary: "Why one person's journey looks like three, and how identity graphs stitch it back together.",
          },
          {
            id: "attribution-offline-to-online",
            slug: "offline-to-online",
            title: "Getting credit for billboards, TV and direct mail",
            minutes: 9,
            summary: "Crediting ads that nobody can click — outdoor, TV, radio and mail.",
          },
          {
            id: "attribution-online-to-offline",
            slug: "online-to-offline",
            title: "Tying an ad click to an in-store purchase",
            minutes: 5,
            summary: "Connecting a click on a phone to a purchase at a till.",
          },
        ],
      },
    ],
  },
  {
    id: "strategy",
    title: "Part V — Strategy",
    subtitle: "You understand the stack. Now decide how your company should get one.",
    sections: [
      {
        id: "buildbuy",
        number: 11,
        bookChapter: 11,
        title: "Build, rent, or buy",
        summary: "The three ways to get an AdTech platform — rent it, acquire it, or build it — and how to choose between them.",
        icon: Scale,
        lessons: [
          {
            id: "buildbuy-the-adtech-dilemma",
            slug: "the-adtech-dilemma",
            title: "The AdTech dilemma: three ways to get a platform",
            minutes: 5,
            summary: "Three ways to get a platform, and the trade-off between speed and control that separates them.",
          },
          {
            id: "buildbuy-renting-a-saas-platform",
            slug: "renting-a-saas-platform",
            title: "Renting: start on someone else's platform",
            minutes: 6,
            summary: "Starting on a rented platform, and the point where the bill overtakes the benefit.",
          },
          {
            id: "buildbuy-buying-an-existing-platform",
            slug: "buying-an-existing-platform",
            title: "Buying: acquire the platform and the team",
            minutes: 6,
            summary: "Acquiring the product, the code and the people, and what comes along with them.",
          },
          {
            id: "buildbuy-building-your-own-platform",
            slug: "building-your-own-platform",
            title: "Building: a platform designed to your workflow",
            minutes: 7,
            summary: "Building to your own workflow, and keeping the first version small enough to actually ship.",
          },
          {
            id: "buildbuy-side-by-side-tradeoffs",
            slug: "side-by-side-tradeoffs",
            title: "Comparing the three paths side by side",
            minutes: 8,
            summary: "The eight criteria that separate the three paths, scored against what your business needs.",
          },
          {
            id: "buildbuy-choosing-your-path",
            slug: "choosing-your-path",
            title: "Which path fits your business?",
            minutes: 10,
            summary: "Four questions — maturity, budget, urgency, control — that point at one answer.",
          },
          {
            id: "buildbuy-key-takeaways-and-upgrade-path",
            slug: "key-takeaways-and-upgrade-path",
            title: "Start small, upgrade strategically",
            minutes: 6,
            summary: "Start rented, replace pieces one at a time, and keep the scope narrow enough to finish.",
          },
        ],
      },
    ],
  },
  {
    id: "appendix",
    title: "Appendix — Beyond the Book",
    subtitle: "A cross-cutting bonus section. Not a book chapter, and not counted toward your progress.",
    sections: [
      {
        id: "ai",
        number: 12,
        bookChapter: 0,
        title: "AI in AdTech",
        summary: "Where machine learning already runs inside the stack you have just learned — bidding, creative, fraud and measurement.",
        icon: Sparkles,
        lessons: [
          {
            id: "ai-why-ai-runs-modern-advertising",
            slug: "why-ai-runs-modern-advertising",
            title: "Why AI runs modern advertising",
            minutes: 7,
            summary: "Why decisions this fast and this numerous are made by models, and which kind of model does what.",
          },
          {
            id: "ai-bidding-and-budget-optimization",
            slug: "bidding-and-budget-optimization",
            title: "How AI decides what to bid and where the money goes",
            minutes: 10,
            summary: "How a model prices one impression, and how it moves budget between campaigns while they run.",
          },
          {
            id: "ai-audiences-and-dynamic-creative",
            slug: "audiences-and-dynamic-creative",
            title: "Finding the right person and building the right ad",
            minutes: 9,
            summary: "Predicting who is worth reaching, then assembling the ad for that specific person.",
          },
          {
            id: "ai-across-every-channel",
            slug: "across-every-channel",
            title: "The same AI, every channel",
            minutes: 8,
            summary: "The same techniques applied to display, video, search, social, mobile, audio and native.",
          },
          {
            id: "ai-fraud-detection-and-traffic-validation",
            slug: "fraud-detection-and-traffic-validation",
            title: "Catching the traffic that was never real",
            minutes: 6,
            summary: "Spotting traffic that was never a person, and the cost of setting the filter too tight.",
          },
          {
            id: "ai-attribution-and-measurement",
            slug: "attribution-and-measurement",
            title: "Proving which ad actually worked",
            minutes: 7,
            summary: "Letting a model, rather than a fixed rule, decide which touchpoint earned the sale.",
          },
        ],
      },
    ],
  },
];
