import { useState } from "react";

import type { LessonContent } from "@/components/journey/lesson-content";
import { cn } from "@/lib/utils";

const BATCH_SIZE = 1000;

/**
 * Each check's fail rate is illustrative, not a benchmark — the lesson says
 * so on screen. What matters is the mechanism: every check removes some
 * share of what came before it, and the remaining count is always computed
 * from these rates, never typed in twice.
 */
const CHECKS = [
  {
    id: "viewability",
    label: "Viewability",
    failRate: 0.32,
    detail: "What percentage of ads were actually viewable to the user, not just loaded off-screen.",
  },
  {
    id: "ivt",
    label: "Invalid traffic (IVT)",
    failRate: 0.08,
    detail: "Whether fraudulent traffic was detected — impressions, clicks, or conversions generated by bots rather than people.",
  },
  {
    id: "geo",
    label: "Geolocation",
    failRate: 0.04,
    detail: "Where the ad actually ran, checked against where the campaign paid to run.",
  },
  {
    id: "brand-safety",
    label: "Brand safety and suitability",
    failRate: 0.03,
    detail: "Whether an ad appeared next to questionable content — illegal or offensive material.",
  },
] as const;

const IAB_ROLES = [
  { title: "Technical standards", text: "Develops the technical specifications that let different AdTech platforms interoperate." },
  { title: "Best practices", text: "Promotes best practices across buyers, sellers, and technology vendors." },
  { title: "Industry research", text: "Conducts research on the state and direction of digital advertising." },
  { title: "Education", text: "Educates companies on the value of digital advertising." },
];

function Body() {
  const [active, setActive] = useState<string[]>([]);

  const toggle = (id: string) =>
    setActive((prev) => (prev.includes(id) ? prev.filter((x) => x !== id) : [...prev, id]));

  const remaining = Math.round(
    CHECKS.filter((c) => active.includes(c.id)).reduce((count, c) => count * (1 - c.failRate), BATCH_SIZE)
  );
  const removed = BATCH_SIZE - remaining;

  return (
    <div className="space-y-8">
      <div className="measure space-y-4 text-muted-foreground">
        <p>
          A served impression is not automatically a good one. Someone still has to check that it
          actually ran, actually appeared on screen, and actually reached a person rather than a bot
          — and that job belongs to a separate layer of the stack from anything covered so far.
        </p>
      </div>

      <section>
        <h3 className="mb-3 text-lg text-foreground">What verification services actually report</h3>
        <p className="measure mb-4 text-muted-foreground">
          Verification services use technology to give advertisers additional information about a
          campaign that already ran. They report:
        </p>
        <ul className="grid gap-2 sm:grid-cols-2">
          {[
            "Which websites the ads appeared on",
            "Where they were displayed (geolocation)",
            "What percentage of ads were viewable by the user",
            "Whether fraudulent traffic was detected — impressions, clicks, or conversions generated by bots",
            "Whether ads appeared next to questionable content, such as illegal or offensive material",
          ].map((point) => (
            <li key={point} className="flex gap-3 text-muted-foreground">
              <span aria-hidden="true" className="mt-2 h-1 w-1 shrink-0 rounded-full bg-primary" />
              <span className="measure">{point}</span>
            </li>
          ))}
        </ul>
        <p className="measure mt-4 text-muted-foreground">
          Separately, measurement and analytics companies analyze a campaign's performance, reach,
          and customer behavior in more depth. That is a different job from the web and in-app
          analytics used to track a site's own traffic — those belong to marketing technology
          (MarTech) — though the two are increasingly converging into unified platforms that cover
          both.
        </p>
      </section>

      <section>
        <h3 className="mb-2 text-lg text-foreground">In the wild</h3>
        <p className="measure text-muted-foreground">
          The book describes a measurement and verification platform built around one reporting
          interface, with panels for reporting, viewability, brand safety and suitability, invalid
          traffic filtering, and geography — tracking more than <span className="figure">500</span>{" "}
          million ads a day. The panel names are not decoration; each one maps to a check below.
        </p>
      </section>

      <section>
        <h3 className="mb-1 text-lg text-foreground">Try it</h3>
        <p className="measure mb-4 text-sm text-muted-foreground">
          Take a batch of <span className="figure">{BATCH_SIZE}</span> served impressions and switch
          verification checks on one at a time. Each one removes a share of what is left — watch how
          few of the original impressions are still billable once every check runs.
        </p>

        <div className="flex flex-wrap gap-2" role="group" aria-label="Toggle verification checks">
          {CHECKS.map((c) => (
            <button
              key={c.id}
              type="button"
              onClick={() => toggle(c.id)}
              aria-pressed={active.includes(c.id)}
              className={cn(
                "min-h-[2.75rem] rounded-lg border px-4 text-left text-sm transition-colors",
                active.includes(c.id)
                  ? "border-primary bg-primary/10 text-foreground"
                  : "border-border text-muted-foreground hover:text-foreground"
              )}
            >
              {c.label}
            </button>
          ))}
        </div>

        <ul className="mt-3 space-y-1">
          {CHECKS.filter((c) => active.includes(c.id)).map((c) => (
            <li key={c.id} className="measure text-sm text-muted-foreground">
              <span className="text-foreground">{c.label}.</span> {c.detail}
            </li>
          ))}
        </ul>

        <div className="mt-4 rounded-lg border border-border bg-card p-5">
          <p className="text-xs uppercase text-muted-foreground">Billable impressions</p>
          <p className="mt-1 text-foreground">
            <span className="figure text-2xl">{remaining}</span>
            <span className="text-muted-foreground"> of </span>
            <span className="figure">{BATCH_SIZE}</span>
          </p>
          <p className="measure mt-2 text-sm text-muted-foreground">
            {active.length === 0
              ? "No checks running yet — every served impression is still counted as-is."
              : `${removed} impressions removed by ${active.length} active check${active.length === 1 ? "" : "s"}.`}
          </p>
        </div>

        <p className="measure mt-3 text-sm text-muted-foreground">
          The fail rates here are illustrative, not a benchmark for any real campaign. What is real is
          the shape of it: verification does not add impressions, it subtracts the ones that should
          never have been billed in the first place.
        </p>
      </section>

      <section>
        <h3 className="mb-3 text-lg text-foreground">Standardization and the IAB</h3>
        <p className="measure mb-4 text-muted-foreground">
          None of the checks above are possible unless every platform in the chain agrees on what a
          viewable impression is, what counts as invalid traffic, and what a category label means. In
          the very early days of online advertising it became clear that a set of shared standards
          was needed, so that different AdTech platforms could communicate efficiently and deliver
          ads in the correct format.
        </p>

        <div className="rounded-lg border border-border bg-card p-4">
          <div className="flex items-center gap-3">
            <span className="figure rounded-lg border border-border bg-secondary px-3 py-1 text-sm text-foreground">
              1996
            </span>
            <p className="measure text-sm text-muted-foreground">
              The Interactive Advertising Bureau (IAB) was founded to standardize the online
              advertising industry.
            </p>
          </div>
        </div>

        <ul className="mt-4 grid gap-2 sm:grid-cols-2">
          {IAB_ROLES.map((role) => (
            <li key={role.title} className="rounded-lg border border-border bg-card p-3">
              <span className="block text-foreground">{role.title}</span>
              <span className="mt-0.5 block text-sm text-muted-foreground">{role.text}</span>
            </li>
          ))}
        </ul>

        <p className="measure mt-4 text-sm text-muted-foreground">
          You already meet IAB standards elsewhere in this stack — the content categories an ad
          network uses as a targeting criterion are IAB categories, agreed on once so that every
          network and every advertiser mean the same thing by them.
        </p>
      </section>
    </div>
  );
}

const lesson: LessonContent = {
  whyThisMatters: (
    <p>
      A campaign report full of impressions is not the same as a campaign that ran well — some share
      of any batch was never viewable, never seen by a person, or ran somewhere the advertiser would
      not have approved. Knowing what verification actually filters out is what stops you from
      reading a raw impression count as the whole story.
    </p>
  ),
  objectives: [
    "List the five things a verification service reports on a served campaign",
    "Distinguish ad verification and measurement from web and in-app analytics",
    "Explain why the IAB was founded and name two of its roles",
  ],
  Body,
  takeaways: [
    "Verification services report which sites an ad ran on, its geolocation, its viewability rate, whether bot traffic was detected, and whether it appeared next to unsuitable content.",
    "Ad measurement and analytics are a separate discipline from the web and in-app analytics that belong to marketing technology, though the two are converging into unified platforms.",
    "The Interactive Advertising Bureau was founded in 1996 to give the industry shared technical standards, best practices, research, and education — the same shared definitions that let verification checks mean the same thing everywhere.",
  ],
  checkYourself: [
    {
      question: "A report shows 100,000 impressions served but only 61,000 counted as billable. What most likely explains the gap?",
      answer: (
        <p>
          One or more verification checks removed the rest — most commonly viewability, since a large
          share of served ads load off-screen or are closed before they are seen. Invalid traffic,
          geolocation mismatches, and brand-safety exclusions typically account for smaller slices of
          the gap.
        </p>
      ),
    },
    {
      question: "Why can't a publisher's own web analytics tool answer whether its ads were brand-safe?",
      answer: (
        <p>
          Web and in-app analytics track how people use a site, not what happened to a specific ad
          impression on it. Brand safety, viewability, and invalid-traffic detection are ad-specific
          checks that require an independent verification vendor sitting between the ad server and
          the report an advertiser trusts.
        </p>
      ),
    },
  ],
};

export default lesson;
